### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by rebaz36** [Flunavgt/ToDoList#5]
# [Morning session: Peer-to-peer code review](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/morning-peer-to-peer-reviews.md)

**Comment by limavfabio** [comment]
Your project is looking great Federico! But I think it would be even better if you implemented a validator for empty inputs and invalid characters. Keep the hard work.
